#!/usr/bin/env bash
# Update the latest release
set -e

USER_CACHE_DIR="${HOME}/.cache/amplipi"
LATEST_RELEASE_FILE="${USER_CACHE_DIR}/latest_release"

# add file if needed
if [ ! -e "${LATEST_RELEASE_FILE}" ]; then
  mkdir -p "${USER_CACHE_DIR}"
  touch "${LATEST_RELEASE_FILE}"
fi

# update the latest release if new
prev_release=$(cat "${LATEST_RELEASE_FILE}")
cur_release=$(curl -s https://api.github.com/repos/micro-nova/AmpliPi/releases/latest | jq -r ".tag_name")
if [ "${cur_release}" != "" ] && [ "${cur_release}" != "null" ] && [ "${cur_release}" != "${prev_release}" ]; then
   echo "${cur_release}" > "${LATEST_RELEASE_FILE}"
fi
