#!/usr/bin/env bash
# Update the latest release
set -e

USER_CACHE_DIR="$HOME/.cache/amplipi"

# add file if needed
if [ ! -e $USER_CACHE_DIR/latest_release ]; then
  mkdir -p $USER_CACHE_DIR
  touch $USER_CACHE_DIR/latest_release
fi

# update the latest release if new
previous_release=$(cat $USER_CACHE_DIR/latest_release)
latest_release=$(curl -s https://api.github.com/repos/micro-nova/AmpliPi/releases/latest | jq -r ".tag_name")
if [ "$latest_release" != "" ] && [ "$latest_release" != "null" ] && [ "$latest_release" != "$previous_release" ]; then
   mkdir -p $USER_CACHE_DIR
   echo "$latest_release" > $USER_CACHE_DIR/latest_release
fi
