#!/usr/bin/env bash

# This script cleans up an AmpliPi unit before it is sent to a customer

set -e

# get directory that the script exists in
cd "$( dirname "$0" )"

HELP="Cleanup filesystem on a remote system defined by USER@HOST (default: pi@amplipi.local)\n
  usage: deploy [USER@HOST]\n
\n
"

user_host='pi@amplipi.local'
user_host_set=false
mock_ctrl=false
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help) echo -e $HELP; exit 0 ;;
    *) if ! $user_host_set; then
          user_host=$1
          user_host_set=true
      else
          echo "Unknown parameter passed: $1";
          echo -e $HELP;
          exit 1
      fi
      ;;
  esac
  shift
done

read -p "Cleaning amplipi filesystem on $user_host, press any key to continue (Ctrl-C to quit)" -n 1
echo "" # newline

# check if amplipi is found
host=$(echo $user_host | sed 's/.*@//')
echo "Checking if $host is found"
ping_loc=$(which ping)
found=false
if [[ "$ping_loc" == /c/Windows/system32/ping ]] && ping -n 2 $host; then
  found=true
elif ping -c 2 $host; then
  found=true
fi
if ! $found; then
  echo ""
  echo "Error: Unable to find $host"
  echo "  On older versions of windows (< 10) you may need to install an MDNS server like Bonjour: https://support.apple.com/kb/DL999?locale=en_US"
  echo "  Some users on windows 10 have reported MDNS does not work over Wifi. Try using a wired connection."
  exit 1;
fi

# setup ssh access if necessary
if ! ssh -o PasswordAuthentication=no $user_host 'echo "AmpliPi has your SSH Key"'; then
  # By default ssh only searches the default keys, lets make sure one of them exist
  if [[ ! -f ~/.ssh/id_ed25519 ]] && [[ ! -f ~/.ssh/id_ecdsa ]] && [[ ! -f ~/.ssh/id_rsa ]]; then
    echo ""
    echo "Generating new ssh key for amplipi"
    ssh-keygen -P '' -N '' -t ed25519 -f ~/.ssh/id_ed25519
  fi
  ssh-copy-id $user_host
fi

echo -e "reverting amplipi back to stock configuration"
ssh $user_host "systemctl --user stop amplipi"
ssh $user_host "rm -f amplipi-dev/house.json*"
ssh $user_host "systemctl --user start amplipi"

echo -e "removing deployments:"
ssh $user_host "rm -f amplipi-*.tar.gz"

echo -e "\ncleaning up amplipi logs:"
ssh $user_host "sudo journalctl --rotate && sleep 1 && sudo journalctl --vacuum-time=1s"

echo -e "\nchanging hostname to amplipi:"
ssh $user_host "sudo sed -i 's/127\.0\.1\.1.*/127.0.1.1       amplipi/' /etc/hosts"
ssh $user_host "sudo sed -i 's/.*/amplipi/' /etc/hostname"

echo -e "\nremoving ssh key and erasing tracks"
ssh $user_host "rm ~/.ssh/* && cat /dev/null > ~/.bash_history && history -c && sudo systemctl poweroff"

echo -e "\nSUCCESS!"
echo -e "AmpliPi unit has been powered off"
