#!/bin/bash
set -e

# get directory that the script exists in
cd "$( dirname "$0" )"

# check if RPI_IP_ADDRESS is set
if [[ -z "${RPI_IP_ADDRESS}" ]]; then
  echo ""
  echo "Please set RPI_IP_ADDRESS, for example:"
  echo -e '\033[1;32mexport RPI_IP_ADDRESS=192.168.0.140\033[0m'
  echo "for ssh key access"
  echo -e '\033[1;32mexport RPI_IP_ADDRESS=pi@192.168.0.140\033[0m'
  echo ""
  exit 1
fi

# TODO: deploy amplipi as a python installed package with pip or something similar

# Home folder on AmpliPi controller
RPI_HOME_FOLDER=/home/pi

# set ENABLE_HW flag since this is being deployed to a machine with the actual hardware setup
sed -i 's/DISABLE_HW = True/DISABLE_HW = False/' ../amplipi/rt.py

poetry build

# copy stuff to board
ssh $RPI_IP_ADDRESS "rm -f amplipi-*.tar.gz"
scp ../dist/amplipi-*.tar.gz $RPI_IP_ADDRESS:
ssh $RPI_IP_ADDRESS "tar -xvf amplipi-*.tar.gz"
ssh $RPI_IP_ADDRESS "chmod +x amplipi-*/scripts/install_deps.bash"
ssh $RPI_IP_ADDRESS "./amplipi-*/scripts/install_deps.bash"


sed -i 's/DISABLE_HW = False/DISABLE_HW = True/' ../amplipi/rt.py
