#!/bin/bash
# get directory that the script exists in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# run the script from the base directory
cd ${SCRIPT_DIR}/..
# for some reason flask loads the app twice if reload option enabled (by default with debugging)
FLASK_ENV=development FLASK_DEBUG=1 FLASK_APP="app:create_app()" flask run --host 0.0.0.0 --no-reload
