#!/bin/bash

# get directory that the script exists in
cd "$( dirname "$0" )/.."
source venv/bin/activate

# Run pylint to check for code issues
pylint --exit-zero amplipi --generated-members "signal.Signals,GPIO.*"
pylint -E amplipi --generated-members "signal.Signals,GPIO.*"

# Lint with mypy, static type checker
mypy amplipi --ignore-missing-imports

# Live tests require some amplipi streams to be setup
pytest -vvv tests/test_ctrl.py # test control separately to avoid weird shared state issues
pytest -vvv -k 'not _live' --ignore 'tests/test_ctrl.py'
pytest -vvv -k '_live'
