#!/bin/bash

# get directory that the script exists in
cd "$( dirname "$0" )/.."
source venv/bin/activate

# Run pylint to check for code issues
pylint amplipi

# Lint with mypy, static type checker
mypy amplipi --ignore-missing-imports

pytest -vvv -k 'not _live'
pytest -vvv -k '_live'
