#!/usr/bin/env python3
# This is a separate script as it must be run with root privileges
# Example: sudo python check_pass 'raspberry'

import crypt
import spwd
import sys

default_password = sys.argv[1]
current_password = spwd.getspnam('pi').sp_pwd
if crypt.crypt(default_password, current_password) == current_password:
  sys.exit(0)
sys.exit(1)
