# Ensure the preamp firmware at least builds.
# It would be nice to eventually add dedicated test AmpliPi hardware
# that Github can target and run real tests on.

name: CMake
on: pull_request
jobs:
  preamp-build:
    name: Build Preamp firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake
        wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
        sudo tar -xf arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz -C /usr/share
        sudo ln -s /usr/share/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-* /usr/bin

    - name: Build Preamp
      run: |
        cmake -S ${{github.workspace}}/fw/preamp -B ${{github.workspace}}/fw/preamp/build
        cmake --build ${{github.workspace}}/fw/preamp/build -j $(nproc)
