name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc-arm-none-eabi
        sudo apt-get -y install cmake

    - name: Build Preamp
      run: |
        cmake -S ${{github.workspace}}/fw/preamp -B ${{github.workspace}}/fw/preamp/build
        cmake --build ${{github.workspace}}/fw/preamp/build -j $(nproc)
